name: multisite
recipe: drupal10
config:
  php: "8.2"
  composer_version: "2.6.5"
  via: apache
  webroot: web
  database: mysql:8.0
  drush: false
  xdebug: false
services:
  appserver:
    scanner: false
    build:
      - composer install
    overrides:
      volumes:
        - /var/local/projects/multisites_govba/sites:/app/web/sites
  node:
    type: node:18
    build_as_root:
      - apt-get update -y
      - apt-get install ruby-full -y
      - gem install compass
  database:
    type: mysql:8.0
    portforward: true
    configuration:
      properties:
        max_allowed_packet: 77
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        PMA_HOST: database
        PMA_USER: root
tooling:
  drush:
    service: appserver
    description: Run Drush commands
    cmd: drush
  ruby:
    service: node
  compass:
    service: node
  site-create <site>:
    service: appserver
    description: Configure a new Drupal site
    cmd: lando/scripts/site-create
  sc <site>:
    service: appserver
    description: Configure a new Drupal site
    cmd: lando/scripts/site-create
  site-update <site>:
    service: appserver
    description: Update a Drupal site with new splitted configs
    cmd: lando/scripts/site-update
  su <site>:
    service: appserver
    description: Update a Drupal site with new splitted configs
    cmd: lando/scripts/site-update
proxy:
  appserver:
    - saeb.multisite.local
    - setre.multisite.local
    - secult.multisite.local
    - oge.multisite.local
    - sema.multisite.local
    - sec.multisite.local
