<?php

/**
 * @file
 * Primary module hooks for Bagov Base Blocks module.
 */

use Drupal\bagov_base_blocks\BagovHelpers;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function bagov_base_blocks_theme()
{
    return BagovHelpers::getThemeHooks();
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function bagov_base_blocks_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $suggestions[] = 'page__' . $node->bundle();
    }
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bagov_base_blocks_theme_suggestions_views_view(array $variables) {
    $suggestions = [];
    $view = $variables['view'];
  
    $suggestions[] = 'views_view__' . $view->id();
    $suggestions[] = 'views_view__' . $view->current_display;
    $suggestions[] = 'views_view__' . $view->id() . '__' . $view->current_display;
  
    return $suggestions;
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function bagov_base_blocks_theme_suggestions_region_alter(array &$suggestions, array $variables)
{
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node && $variables['elements']['#region'] == 'content') {
        $suggestions[] = 'region__content__' . $node->bundle();
    }
}

/**
 * Implements hook_entity_field_storage_info_alter().
 */
function bagov_base_blocks_entity_field_storage_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {

    // --- Opções do campo "Região do Banner"
    $options_regiao_banner = [
                'banner_top_1400x310' => t('Banner Superior (1400x310)'),
                'banner_middle_1400x310' => t('Banner Centro (1400x310)'),
                'banner_bottom_1400x310' => t('Banner Inferior (1400x310)'),
                'banner_fixed_duplex 700x420' => t('Banner Fixo Duplo (700x420)'),
                'banner_fixed_quadruple_200x115' => t('Banner Fixo Quádruplo (200x115)'),
                'banner_card_icons' => t('Carrossel Card de Ícones')
            ];
  
    // --- Opções do campo "Target do Link"
    $options_link_target = ['_self' => t('Abrir na Mesma Página'),
            '_blank' => t('Abrir em Nova Página'),
            ];
  
    if($entity_type->id() == 'node') {
  
      if(isset($fields['field_regiao_banner'])) {
        $fields['field_regiao_banner']->setSetting('allowed_values', $options_regiao_banner);
      }
  
      if(isset($fields['field_link_target'])) {
        $fields['field_link_target']->setSetting('allowed_values', $options_link_target);
      }
    }
  }

function bagov_base_blocks_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id){

  if($form_id == 'block_form'){

    if($form["id"]["#default_value"] == "bagov_base_views_block__videos_do_youtube_player_home"){
     
      $config = getYoutubeBlockConfig(); 

      $input = &$form_state->getUserInput()['mais_videos'];
      $url = isset($input) ? $input : $config->get('url');
      $config->set('url', $url)->save();
      $form['mais_videos'] = [        
          '#type' => 'textfield',
          '#default_value' => $url,
          '#title' => t('Endereço do do youtube'),
          '#description' => t('Endereço completo da página do youtube da secretaria, por exemplo: <a href="https://www.youtube.com/@governodabahia">https://www.youtube.com/@governodabahia</a>'),            
      ];
    }
  }
}

function getYoutubeBlockConfig(){
  return \Drupal::service('config.factory')->getEditable('bagovblocks.youtube');
}