<?php

/**
 * @file
 * Primary module hooks for Bagov Base Blocks module.
 */

use Drupal\bagov_base_blocks\BagovHelpers;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;


/**
 * Implements hook_theme().
 */
function bagov_base_blocks_theme()
{
    return BagovHelpers::getThemeHooks();
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function bagov_base_blocks_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $suggestions[] = 'page__' . $node->bundle();
    }
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bagov_base_blocks_theme_suggestions_views_view(array $variables) {
    $suggestions = [];
    $view = $variables['view'];
  
    $suggestions[] = 'views_view__' . $view->id();
    $suggestions[] = 'views_view__' . $view->current_display;
    $suggestions[] = 'views_view__' . $view->id() . '__' . $view->current_display;
  
    return $suggestions;
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function bagov_base_blocks_theme_suggestions_region_alter(array &$suggestions, array $variables)
{
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node && $variables['elements']['#region'] == 'content') {
        $suggestions[] = 'region__content__' . $node->bundle();
    }
}
