<?php

use Drupal\views\Views;

/**
 * @file
 * Tema de Notícias theme file.
 */

/**
 * Preprocess page content noticias.
 *
 * @param array $vars
 *   An associative array containing:
 *   - node: A Node object.
 */
function bagov_base_preprocess_page__noticias(array &$vars)
{
    $vars['#attached']['library'][] = 'bagov_base/noticias';
    $view = Views::getView('noticias');
    $vars['page']['content'] = $view->render('page_noticias');  
}
