# Schema for the configuration files of the Text Resize module.

bagov_base_blocks.settings:
  type: config_object
  label: 'Bagov Base settings'
  mapping:
    enable_contrast_button:
      type: boolean
      label: 'Display contrast button'
